apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "streaming-kafka.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "streaming-kafka.name" . | quote }}
