image:
  repository: bitnami/kafka
  tag: "3.7.1"
  pullPolicy: IfNotPresent

service:
  port: 9092
  controllerPort: 9093

kafka:
  clusterId: MkU3OEVBNTcwNTJENDM2Qk
  autoCreateTopicsEnable: true
  numPartitions: 3
  logRetentionHours: 24

persistence:
  enabled: true
  size: 8Gi
  storageClassName: ""

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1536Mi
