apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streaming-minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "streaming-minio.labels" . | indent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.auth.rootUser | quote }}
  root-password: {{ .Values.auth.rootPassword | quote }}
