apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "streaming-minio.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: console
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "streaming-minio.name" . | quote }}
