{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "streaming-pipeline.fullname" . }}-drivers
  namespace: {{ default .Release.Namespace .Values.metrics.podMonitor.namespace }}
  labels:
{{ include "streaming-pipeline.labels" . | indent 4 }}
{{- with .Values.metrics.podMonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      spark-role: {{ .Values.metrics.podMonitor.selector.sparkRole | quote }}
      streaming-query: {{ .Values.metrics.podMonitor.selector.streamingQuery | quote }}
  podMetricsEndpoints:
{{- range $endpoint := .Values.metrics.podMonitor.endpoints }}
    - path: {{ $endpoint.path | quote }}
      targetPort: {{ $endpoint.targetPort }}
      interval: {{ default $.Values.metrics.podMonitor.interval $endpoint.interval | quote }}
      scrapeTimeout: {{ default $.Values.metrics.podMonitor.scrapeTimeout $endpoint.scrapeTimeout | quote }}
{{- end }}
{{- end }}
